---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: shell.upbound.io
spec:
  compositeTypeRef:
    apiVersion: upbound.io/v1alpha1
    kind: XShell
  mode: Pipeline
  pipeline:
    - step: shell
      functionRef:
        # When installed through a package manager, use
        # name: crossplane-contrib-function-shell
        name: function-shell
      input:
        apiVersion: shell.fn.crossplane.io/v1alpha1
        kind: Parameters
        shellScriptsConfigMapsRef:
          - scriptNames:
              - hello-from-python.py
              - get-datadog-dashboard-ids.sh
            name: function-shell-script
            namespace: upbound-system
        shellEnvVarsSecretRef:
          key: credentials
          name: datadog-secret
          namespace: upbound-system
        shellEnvVars:
          - key: DATADOG_API_URL
            value: "https://api.datadoghq.com/api/v1/dashboard"
        shellCommand: |
          /scripts/get-datadog-dashboard-ids.sh
          python3 /scripts/hello-from-python.py|awk '{print $3}'|tr "p" "P"
        stdoutField: status.atFunction.shell.stdout
        stderrField: status.atFunction.shell.stderr
