apiVersion: v1
kind: ConfigMap
metadata:
  name: function-shell-script
data:
  hello-from-python.py: |
    #!/usr/bin/python3

    print ( "hello from python" )
  get-datadog-dashboard-ids.sh: |
    #!/bin/bash

    curl -X GET "${DATADOG_API_URL}" \
      -H "Accept: application/json" \
      -H "DD-API-KEY: ${DATADOG_API_KEY}" \
      -H "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}"|\
      jq '.dashboards[] .id';
